<?php
// ---------------------------------------------------------------
// The following items need to be changed to match your website
// ---------------------------------------------------------------
// Location and URL of your homepage index and logo
$image_webhome	= '<a href="./index.php"><img src="./images/logo.png" title="PCSysBlog" alt="logo.png" style="border: 0px solid ; width: 200px; height: 67px;" align="middle" /></a>';
// Name & Description of your site
$site_name	= 'The name of your site';
$site_description = ' :: The description of your site';
// Url for your blog
$site_url = 'http://where_you_put_pcsysblog';
// Site administrators email address
$admin_email = 'admin@mydomain.com';
// Footer copyright - DON'T CHANGE THIS
$copyright = 'Powered by: <a href="../pcsysblog/">PCSysBlog-0.0.1a</a> &copy; 2004-2008 - All rights reserved.<br />PCSysBlog is Free Software released under the <a href="http://www.gnu.org/licenses/gpl.txt">GNU/GPL license</a>.';
// XHTML compliance indicator
$xhtml_compliance = '<a href="http://validator.w3.org/check?uri=referer"><img src="./images/vxhtml10.png" alt="Valid XHTML 1.0!" height="31" width="88" style="border-style:none" /></a>';
// CSS compliance indicator
$vcss_compliance = '<a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.pcsysadmin.com/pcsysblog/includes/pcsysblog.css"><img style="border:0;width:88px;height:31px" src="./images/vcss.png" alt="Valid CSS!" /></a>';
// Style sheet for your blog
$style_sheet = '<link rel="stylesheet" type="text/css" href="./includes/pcsysblog.css" />';
// Site navigation links at the top and bottom of the page
$nav_links	= '<span style="font-size: small"><a href="index.php">Home</a> | <a href="index.php?url=post">Post</a> | <a href="index.php?url=register">Register</a> | <a href="index.php?url=login">Login</a> | <a href="logout.php">Logout</a></span>';
// Open the table for the site name/description
$header_open_table1 = '<table style="text-align: left; width: 100%;" border="0" cellspacing="0" cellpadding="2"><tr><td style="width: 75%; text-align: left; vertical-align: top; font-size: x-large;">';
// Open the table for the date
$header_open_table2 = '<td style="width: 25%; text-align: right; vertical-align: top; font-size: small;">';
// Close the table for the site name/description
$header_close_table1 = '</td>';
// Close the table for the date
$header_close_table2 = '</td></tr></table>';
// Open the table for the navlinks
$navlinks_open_table = '<table style="width: 100%; text-align: right;" border="0" cellspacing="0" cellpadding="2"><tr><td style="vertical-align: top; background-color: #734646;">';
// Close the table for the navlinks
$navlinks_close_table = '</td></tr></table>';
// Open the table for the blog display
$blog_open_table1= '<table style="text-align: left; width: 100%;" border="0" cellspacing="0" cellpadding="0"><tr><td style="width: 75%; text-align: left; vertical-align: top;">';
// Close the table for the blog display
$blog_close_table1 = '</td></tr></table>';
// Open the table for the copyright info
$footer_open_table1 = '<table style="text-align: left; width: 100%;" border="0" cellspacing="0" cellpadding="2"><tr><td style="width: 75%; text-align: left; vertical-align: top; font-size: xx-small;">';
// Open the table for the XHTML compliance indicator
$footer_open_table2 = '<td style="width: 25%; text-align: right; vertical-align: top;">';
// Close the table for the copyright info
$footer_close_table1 = '</td>';
// Close the table for the XHTML compliance indicator
$footer_close_table2 = '</td></tr></table>';
?>
